In [29]:
import numpy as np   
import pandas as pd
import tensorflow as tf

In [30]:
tf.__version__

'2.11.0'

In [31]:
df = pd.read_excel('/content/ann.xlsx')  #combined cycle power plant dataset
X = df.iloc[:, :-1].values            # features are temperature,pressure,humidity,exhaust vaccum,energy output
y = df.iloc[:, -1].values

In [32]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [33]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [35]:
ann = tf.keras.models.Sequential()  #from keras library

In [36]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu')) 

In [37]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu')) 

In [38]:
ann.add(tf.keras.layers.Dense(units = 1))  #no activation for regression for classification of binary use sigmoid else use soft max function

In [39]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')  # loss = MSE for regression

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 22134.8574
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 194.9318
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 187.7394
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 179.0909
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 168.8105
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 157.8611
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 145.8643
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 132.6554
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 119.3909
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 106.7271
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 93.4718
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - los

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))